// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: any.proto
#ifndef GRPC_any_2eproto__INCLUDED
#define GRPC_any_2eproto__INCLUDED

#include "any.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace any {

class Any final {
 public:
  static constexpr char const* service_full_name() {
    return "any.Any";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status send_any(::grpc::ClientContext* context, const ::any::request& request, ::any::reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::any::reply>> Asyncsend_any(::grpc::ClientContext* context, const ::any::request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::any::reply>>(Asyncsend_anyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::any::reply>> PrepareAsyncsend_any(::grpc::ClientContext* context, const ::any::request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::any::reply>>(PrepareAsyncsend_anyRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void send_any(::grpc::ClientContext* context, const ::any::request* request, ::any::reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void send_any(::grpc::ClientContext* context, const ::any::request* request, ::any::reply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::any::reply>* Asyncsend_anyRaw(::grpc::ClientContext* context, const ::any::request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::any::reply>* PrepareAsyncsend_anyRaw(::grpc::ClientContext* context, const ::any::request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status send_any(::grpc::ClientContext* context, const ::any::request& request, ::any::reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::any::reply>> Asyncsend_any(::grpc::ClientContext* context, const ::any::request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::any::reply>>(Asyncsend_anyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::any::reply>> PrepareAsyncsend_any(::grpc::ClientContext* context, const ::any::request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::any::reply>>(PrepareAsyncsend_anyRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void send_any(::grpc::ClientContext* context, const ::any::request* request, ::any::reply* response, std::function<void(::grpc::Status)>) override;
      void send_any(::grpc::ClientContext* context, const ::any::request* request, ::any::reply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::any::reply>* Asyncsend_anyRaw(::grpc::ClientContext* context, const ::any::request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::any::reply>* PrepareAsyncsend_anyRaw(::grpc::ClientContext* context, const ::any::request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_send_any_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status send_any(::grpc::ServerContext* context, const ::any::request* request, ::any::reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_send_any : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_send_any() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_send_any() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_any(::grpc::ServerContext* /*context*/, const ::any::request* /*request*/, ::any::reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsend_any(::grpc::ServerContext* context, ::any::request* request, ::grpc::ServerAsyncResponseWriter< ::any::reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_send_any<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_send_any : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_send_any() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::any::request, ::any::reply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::any::request* request, ::any::reply* response) { return this->send_any(context, request, response); }));}
    void SetMessageAllocatorFor_send_any(
        ::grpc::MessageAllocator< ::any::request, ::any::reply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::any::request, ::any::reply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_send_any() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_any(::grpc::ServerContext* /*context*/, const ::any::request* /*request*/, ::any::reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* send_any(
      ::grpc::CallbackServerContext* /*context*/, const ::any::request* /*request*/, ::any::reply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_send_any<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_send_any : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_send_any() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_send_any() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_any(::grpc::ServerContext* /*context*/, const ::any::request* /*request*/, ::any::reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_send_any : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_send_any() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_send_any() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_any(::grpc::ServerContext* /*context*/, const ::any::request* /*request*/, ::any::reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsend_any(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_send_any : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_send_any() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->send_any(context, request, response); }));
    }
    ~WithRawCallbackMethod_send_any() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_any(::grpc::ServerContext* /*context*/, const ::any::request* /*request*/, ::any::reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* send_any(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_send_any : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_send_any() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::any::request, ::any::reply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::any::request, ::any::reply>* streamer) {
                       return this->Streamedsend_any(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_send_any() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status send_any(::grpc::ServerContext* /*context*/, const ::any::request* /*request*/, ::any::reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedsend_any(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::any::request,::any::reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_send_any<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_send_any<Service > StreamedService;
};

}  // namespace any


#endif  // GRPC_any_2eproto__INCLUDED
